### ISSUE TITLE
Inserting a space between the value and the symbol (ofstream overload operator and SI::to_string() function)

### ISSUE THREAD

**Issue by sergioferrari** [bernedom/SI#108]
Personally in the output stream (include file: <stream.h>) I would insert a space between the value and the symbol of the variable so that it looks like this: 
```
SI::kilo_gram_t mymass(3.2);
std::cout << mymass << std::endl;
// output: 3.2 kg
```
The same applies to overloading the to_string() function

**Comment by bernedom** [comment]
You are right. This is even described in section 5.4.2 of the SI brochure : 
> The numerical value always precedes the unit and a space is always used to separate the
unit from the number 

Will fix it as soon as I find the time for it
