### ISSUE TITLE
a=F/m compile error

### ISSUE THREAD

**Issue by bladan** [bernedom/SI#38]
Trying to calculate acceleration from force divided by mass (Newton's second law), but it gives me a compile error.

When I try to add:
`BUILD_UNIT_FROM_DIVISON(acceleration_t, force_t, mass_t)`
...in `acceleration.h`, I get even more compiler errors, looks like an issue where header include orders.

Reproduced in "SI" version 1.4.1, using clang 7.0.1-8, gcc 8.3.0 and VS2019 16.4.3

**Comment by bladan** [comment]
Adding:
`BUILD_UNIT_FROM_DIVISON(acceleration_t, velocity_squared_t, length_t)`
in acceleration.h seems to work. Looks like `#include "force.h"` causes the issue.

**Comment by bernedom** [comment]
Building a = F/m is already implemented in force.h so adding it again will lead to compiler errors bevause of  duplicate symbols. You need to include "force.h" as it is defined there. 
Granted, finding the correct header is sometimes difficult in SI, so if you have a proposal on how to simplify, you're welcome.

See here for a test that builds acceleration from F/m
https://github.com/bernedom/SI/blob/26eb0f0e2c262193480ec788f12dab8f6e9b9c14/test/src/derived_unit_tests/force_tests.cc#L192

**Comment by bladan** [comment]
Can confirm this solves the problem.

Would have been expected to see the definition of derived data types in derived data types header.
Such as
force.h
- BUILD_UNIT_FROM_MULTIPLICATION(force_t, mass_t, acceleration_t)
acceleration.h
+BUILD_UNIT_FROM_DIVISON(acceleration_t, force_t, mass_t)

Similarly, I extended:

velocity.h
+template <typename _type, typename _ratio>
+using velocity_squared_t = detail::unit_t<'v', 2, _type, _ratio>;

acceleration.h
+BUILD_UNIT_FROM_DIVISON(acceleration_t, velocity_squared_t, length_t)
