### ISSUE TITLE
Wrong implementation of comparison operators > and <

### ISSUE THREAD

**Issue by bladan** [bernedom/SI#43]
There seems to be an issue with comparison operators. Following code runs into else() clause.
```
    auto _SPEED_10_KM_H = 10.0_km / 1.0_h;
    auto _SPEED_80_KM_H = 80.0_km / 1.0_h;
    if (_SPEED_10_KM_H < _SPEED_80_KM_H)
    {
        std::cout << "10 km/h < 80 km/h";
    }
    else
    {
        std::cout << "10 km/h >= 80 km/h";
    }
```
Reproduced in "SI" version 1.4.1, using clang 7.0.1-8, gcc 8.3.0 and VS2019 16.4.3

**Comment by bernedom** [comment]
Can confirm, does not work as expected, will investigate.

Seems to be a problem with units with a ratio that are not properly dividable by 10 (which are most common time units)
