### ISSUE TITLE
Unit test typo

### ISSUE THREAD

**Issue by pjanck** [bernedom/SI#81]
https://github.com/bernedom/SI/blob/fce11bcbaf74854f0180db92865b14eba1853f9e/test/src/base_unit_tests/length_tests.cc#L21

I assume the comment should say `_fm` checking for femtometers. Here the whole block as a reference:

https://github.com/bernedom/SI/blob/fce11bcbaf74854f0180db92865b14eba1853f9e/test/src/base_unit_tests/length_tests.cc#L21-L31

I really like your use of compile-time unit testing!

**Comment by bernedom** [comment]
Thank you for the close look and paying attention :+1: .Will be fixed in the next minor release.
